config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :notes

  authenticated :user do
    root 'notes#index', as: :authenticated_root
  end
  root 'welcomes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, except: [:index, :new, :create]

  def index
    @notes = Note.all.order("created_at DESC")
  end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.create(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def require_same_user
    if current_user != @note.user
      redirect_to root_path
    end
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    @notes = Note.all
    @example_notes = Note.where(user_id: 4)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Dzenote
  = stylesheet_link_tag    'application',
  media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to image_tag('dzenote.png', height: '33'), root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "Add Note", new_note_path
          = link_to current_user.email, edit_user_registration_path
          = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log in", new_user_session_path
  - if controller.controller_name != 'welcomes'
    = render 'layouts/messages'
  - if devise_controller?
    .wrapper_with_padding
      = yield
  - else
    = yield

app/views/notes/_example_notes.html.haml
- @example_notes.each do |note|
  %a{ href: (url_for [note])}
    .note
      %p.title= note.title
      %p.mini-content
        = truncate(note.content, length: 110)
      %p.date
        Created
        = time_ago_in_words(note.created_at)
        ago.

app/views/notes/_form.html.haml
= simple_form_for(@note) do |f|
  = f.text_field :title
  = f.text_area :content
  = f.submit class: "button"

app/views/notes/edit.html.haml
.wrapper_with_padding
  %h1 Edit Note
  = render 'form'
  = link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    - unless current_user.notes.blank?
      - current_user.notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.mini-content
              = truncate(note.content, length: 110)
            %p.date
              Created
              = time_ago_in_words(note.created_at)
              ago.
    - else
      %h2 Write something.
      %p Add a note and have an access to it from any place in the world.
      .button-field
        = link_to "Add Note", new_note_path, class: "button"

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 Add A Note
  = render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @note.title
    %p= simple_format(@note.content)
    .buttons
      = link_to "Edit", edit_note_path(@note), class: "button"
      = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button-delete"

app/views/welcomes/index.html.haml
#banner
  .banner_content
    %h1 DZENOTE
    %p Your 24/7 access to pen and paper.
    = link_to "Sign Up", new_user_registration_path, class: "button"
#testimonial
  .wrapper
    %p.quote I created this app for my own needs. Since Evernote-like cloud
    services became quite heavy for writing simple things down.
    %p.name - Petr
#middle_cta
  #notes
    .wrapper
      %h2 Example notes list
      = render 'notes/example_notes'
#bottom_cta
  .wrapper
    %h2 Sign up in 10 sec.
    %p Simply put your email & password and start using pen and paper.
    = link_to "Why not?", new_user_registration_path, class: "button"
%footer
  %p &copy; DZENOTE